sudo: false
language: node_js

env:
  - NODE_ENV=production
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"
  - "9"

before_install:
  - travis_retry npm install

install:
  - npm install mocha istanbul standard
  - npm install babel-cli babel-preset-env babel-preset-es2015
  - npm install -g check-node-version
  - npm install -g codecov

script:
  - bin/test-and-build.sh --ci
  - (check-node-version --node '>=8.0.0' && codecov); echo '---'

matrix:
  allow_failures:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "4"
